stages:
- name: assignment2-stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: assignment2-ver1
    when:
      branch:
        include:
        - main
timeout: 60
notification: {}
